export const Users = [
    {
      id:1,
      profilePicture: "persons/1.jfif",
      username: "Keya Mitra",
    },
    {
      id:2,
      profilePicture: "persons/2.jfif",
      username: "sumana Ghosh",
    },
    {
      id:3,
      profilePicture: "persons/3.jpg",
      username: "Robin Poddar",
    },
    {
      id:4,
      profilePicture: "persons/4.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "persons/5.jfif",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "persons/6.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "persons/7.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "persons/8.jpg",
      username: "Kristen Thomas",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/1.jfif",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
 ];